---
- name: "Install the {{ package }} package"
  yum: 
    name: "{{ package }}"
    state: latest

- name: "Start the {{ service }} service"
  service:
    name: "{{ service }}"
    enabled: yes
    state: started