---
- name: Install the firewall
  yum:
    name: "{{ firewall_pkg }}"
    state: latest

- name: Start the firewall
  service:
    name: "{{ firewall_svc }}"
    enabled: yes
    state: started

- name: Open the port for {{ rule }}
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ rule }}"    