---
- name: Task Failure Exercise
  hosts: databases
  gather_facts: no
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check local time
      command: date
      register: command_result
      changed_when: false

    - name: print local time
      debug:
        var: command_result.stdout

    - name: Attempt to set up a web server
      block:
        - name: Install web packages
          yum:
            name: "{{ web_package }}"
            state: present
          failed_when: web_package == "httpd"            
      rescue:
        - name: Install db packages
          yum:
            name: "{{ db_package }}"
            state: present
      always:
        - name: Start DB service
          service:
            name: "{{ db_service }}"
            state: started            