---
- name: MariaDB server is installed
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
    resource_url: "http://ansible.example.com" 
    config_file_url: "{{ resource_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
  tasks:
    # 1) 패키지 설치 - mariadb-server, python3-PyMySQL
    - name: "{{ db_packages }} packages are installed."
      yum:
        name: "{{ db_packages }}"
        state: present
      notify:
        - set db password        

    # 2) 서비스 기동 - mariadb.service
    - name: "Make sure the database service is running"
      service:
        name: "{{ db_service }}"
        state: started
        enabled: yes

    # 3) 설정 파일 가져오기 - http://192.168.10.10/my.cnf.standard -> /etc/my.cnf
    #   - notify ~ handler
    - name: "The {{ config_file_dst }} file has been installed"
      get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart db service

  handlers:
    - name: restart db service         
      service: 
        name: "{{ db_service }}"
        state: restarted

    - name: set db password
      mysql_user:
        name: root
        password: soldesk1.
