---
- name: "웹서비스 복구"
  hosts: webservers
  vars_files:
  - vars/vars.yml
  tasks:
  # 1) 패키지 삭제 - httpd, mod_ssl
  # 2) 웹 소스 삭제 - /var/www/html/index.html
  # 3) 방화벽 서비스 해제 - http, https
  - name: "패키지 삭제 - httpd, mod_ssl"
    yum:
      name: 
      - "{{ pkg_web }}"
      - "{{ pkg_web_mod }}"
      state: absent
  - name: "2) 웹 소스 삭제 - /var/www/html/index.html"
    file:
      path: "{{ file_web_src_file }}"
      state: absent
  - name: "3) 방화벽 서비스 해제 - http, https"
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: disabled
      immediate: yes
    loop:
    - "{{ fw_http }}"
    - "{{ fw_https }}"

      



